
package com.tririga.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-11T17:47:51.268+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "InvalidContinuationTokenException", targetNamespace = "http://ws.tririga.com")
public class InvalidContinuationTokenException extends java.lang.Exception {

    private com.tririga.ws.errors.InvalidContinuationTokenException faultInfo;

    public InvalidContinuationTokenException() {
        super();
    }

    public InvalidContinuationTokenException(String message) {
        super(message);
    }

    public InvalidContinuationTokenException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidContinuationTokenException(String message, com.tririga.ws.errors.InvalidContinuationTokenException invalidContinuationTokenException) {
        super(message);
        this.faultInfo = invalidContinuationTokenException;
    }

    public InvalidContinuationTokenException(String message, com.tririga.ws.errors.InvalidContinuationTokenException invalidContinuationTokenException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidContinuationTokenException;
    }

    public com.tririga.ws.errors.InvalidContinuationTokenException getFaultInfo() {
        return this.faultInfo;
    }
}
