package com.tririga.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-11T17:47:51.450+05:30
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "TririgaWS",
                  wsdlLocation = "file:wsdls/TririgaWS.wsdl",
                  targetNamespace = "http://ws.tririga.com")
public class TririgaWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.tririga.com", "TririgaWS");
    public final static QName TririgaWSPort = new QName("http://ws.tririga.com", "TririgaWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdls/TririgaWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TririgaWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdls/TririgaWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TririgaWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TririgaWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TririgaWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TririgaWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TririgaWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TririgaWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TririgaWSPortType
     */
    @WebEndpoint(name = "TririgaWSPort")
    public TririgaWSPortType getTririgaWSPort() {
        return super.getPort(TririgaWSPort, TririgaWSPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TririgaWSPortType
     */
    @WebEndpoint(name = "TririgaWSPort")
    public TririgaWSPortType getTririgaWSPort(WebServiceFeature... features) {
        return super.getPort(TririgaWSPort, TririgaWSPortType.class, features);
    }

}
